---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespaces/namespaces.yaml
  - ./helmrepos/openebs.yaml
  - ./metallb/metallb.yaml
  - ./openebs/openebs.yaml
  - ./podinfo/podinfo.yaml
