---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./flux-system
  - ./namespaces/kflux.yaml
  - ./metallb/kflux.yaml
  - ./openebs/kflux.yaml
  - ./cnpg/kflux.yaml
  - ./podinfo/kflux.yaml
  - ./monitoring/kflux.yaml
  - ./ingress/kflux.yaml
